version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app/src
      - ./backend/test:/app/test
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - 3005:80
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

  db:
    image: postgres:14.2-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432
