version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:14.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    restart: always
    image: adminer:latest
    environment:
      ADMINER_PLUGINS: 'dump-json'
      ADMINER_DESIGN: 'rm-soft'
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:8080

  minio:
    image: bitnami/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
volumes:
  postgres_db:

  minio_data:
    driver: local
