version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:14.5
    environment:
      POSTGRES_USER: 'task_user_v2'
      POSTGRES_PASSWORD: 'task_password_v2'
      POSTGRES_DB: 'task_manager_v2'

  backend:
    restart: always
    build:
      context: ./
      dockerfile: ./apps/backend/Dockerfile
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - postgres

  frontend:
    restart: always
    build:
      context: ./
      dockerfile: ./apps/frontend/Dockerfile
      args:
        VITE_API_URL: 'http://localhost:3000'
    ports:
      - 3005:8080
    depends_on:
      - backend
