version: '3.8'

services:
  adminer:
    restart: always
    image: adminer:latest
    networks:
      - caddy
      - doctoo
    labels:
      caddy: adminer.doctoo.org
      caddy.reverse_proxy: '{{upstreams 8080}}'
      caddy.basicauth: '*'
      caddy.basicauth.radency: '$ADMINER_PASSWORD'

  postgres:
    restart: always
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - doctoo
    volumes:
      - postgres_prod_db:/var/lib/postgresql/data

  postgres_backup:
    restart: always
    image: satont/postgresql-backup-s3:latest
    environment:
      POSTGRES_DATABASE: 'all'
      POSTGRES_HOST: 'postgres'
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      S3_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
      S3_BUCKET: ${BACKUP_BUCKET_NAME}
      S3_REGION: ${BACKUP_BUCKET_REGION}
      S3_ENDPOINT: ${MINIO_ENDPOINT}
      SCHEDULE: ${BACKUP_SCHEDULE}
      ENCRYPTION_PASSWORD: ${ENCRYPTION_PASSWORD}
    networks:
      - doctoo

  backend:
    restart: always
    image: registry.doctoo.org/radency/doctoo-backend:latest
    environment:
      APP_NAME: ${APP_NAME}
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      DATABASE_URL: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?schema=public'
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_DAYS: ${JWT_EXPIRATION_DAYS}
      JWT_EXPIRATION_TRESHOLD_SECONDS: ${JWT_EXPIRATION_TRESHOLD_SECONDS}
      SALT_ROUNDS: ${SALT_ROUNDS}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SECURE: ${MAIL_SECURE}
      FRONTEND_SIGNUP_PATH: ${FRONTEND_SIGNUP_PATH}
      FRONTEND_CHANGE_EMAIL_PATH: ${FRONTEND_CHANGE_EMAIL_PATH}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
    depends_on:
      - postgres
    networks:
      - caddy
      - doctoo
    labels:
      caddy: https://api.doctoo.org
      caddy.reverse_proxy: '{{upstreams $BACKEND_PORT}}'

  frontend:
    restart: always
    image: registry.doctoo.org/radency/doctoo-frontend:latest
    depends_on:
      - backend
    networks:
      - doctoo
      - caddy
    labels:
      caddy: https://doctoo.org
      caddy.reverse_proxy: '{{upstreams 8080}}'

volumes:
  postgres_prod_db:

networks:
  doctoo:
  caddy:
    external: true
