version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_prod_db:/var/lib/postgresql/data

  backend:
    restart: always
    build:
      context: ./
      dockerfile: ./apps/backend/Dockerfile
    environment:
      PORT: ${BACKEND_PORT}
      DATABASE_URL: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?schema=public'
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - postgres

  frontend:
    restart: always
    build:
      context: ./
      dockerfile: ./apps/frontend/Dockerfile
      args:
        VITE_BACKEND_API_URL: ${VITE_BACKEND_API_URL}
    ports:
      - ${FRONTEND_PORT}:8080
    depends_on:
      - backend

volumes:
  postgres_prod_db:
