-- CreateEnum
CREATE TYPE "AppointmentType" AS ENUM ('CONSULTATION', 'FIRST_VISIT', 'ANNUAL_CHECKUP', 'FOLLOW_UP', 'SPECIALIST_REFERRAL', 'PROCEDURE', 'PREVENTIVE_CARE', 'REHABILITATION', 'TELEMEDICINE');

-- AlterTable
ALTER TABLE "appointments" ADD COLUMN     "type" "AppointmentType" NOT NULL DEFAULT 'CONSULTATION';
