name: Chromatic Tests

on:
  pull_request:
    paths: ['apps/frontend/src/somponents/**', 'apps/frontend/src/pages/**']

jobs:
  chromatic:
    strategy:
      matrix:
        node-version: [18]

    runs-on: self-hosted
    name: Chromatic Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i -r
        working-directory: apps/frontend

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          workingDir: apps/frontend
          buildScriptName: storybook:build
          onlyChanged: true
