name: Internship 2024 Doctoo CI/CD
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js and PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i -r

      - name: Build apps
        run: pnpm build

  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js and PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i -r
      - name: Generate prisma schema
        run: pnpm run prebuild
        working-directory: ./apps/backend

      - name: Run unit tests backend
        run: pnpm run backend:test

      - name: Run e2e tests backend
        run: pnpm run  backend:test:e2e
      - name: Run unit tests frontend
        run: pnpm run  frontend:test
        

       